### PR TITLE
Add multi version build

### PR DESCRIPTION
**Pull request by lumjjb**
Signed-off-by: Brandon Lum <lumjjb@gmail.com>

### CODE REVIEW

**Comment by lumjjb** [comment]
don't merge until testing for older versions are done.

**Comment by lumjjb** [comment]
Tested the image builds - should be ready for review @mrsabath

**Comment by lumjjb** [comment]
Addressing https://github.com/lumjjb/tornjak/issues/33

**Review by mrsabath — APPROVED** [review]
LGTM

**Pull request merged**
